server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/website;
    index index.html;

    location /shared/ {
        alias /usr/share/nginx/html/shared/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
